# Hardcode the resource names to something human friendly 

## Watch these resources for new DNS records 
sources: 
  # - service 
  - ingress 
## use google as the dns provider 
provider: google 
# Specify the Google project (required when provider=google) 
# You'll need to create this secret containing your credentials.json 
google: 
  project: "future-linker-379208" 
  serviceAccountSecret: "sa-secret" 
  serviceAccountSecretKey: "credentials.json" 
  zoneVisibility: "public"
  batchChangeSize: 1000
## List of domains that can be managed. Should be managed by Google Cloud DNS 
domainFilters: ["akzhol7.ml"] 
overwrite: true
foo_features_enabled: true
# These help tell which records are owned by external-dns. 
registry: "txt" 
txtOwnerId: "" 
txtPrefix: "" 
## Limit external-dns resources 

## ensure RBAC is enabled 
rbac: 
  create: true 
  apiVersion: v1 
logLevel: debug 
policy: upsert-only
#policy: sync